name: wtf_sdk
description: Wallet Transfer Framework (WTF) - A Flutter SDK for blockchain payments and transfers with AI integration
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # For making HTTP requests to blockchain APIs
  web3dart: ^2.7.1  # For Ethereum blockchain interactions
  tron: ^2.0.0  # For TRON blockchain interactions
  solana: ^0.30.0  # For Solana blockchain interactions
  sui: ^0.1.0  # For Sui blockchain interactions
  bitcoin_flutter: ^2.0.3  # For Bitcoin blockchain interactions
  kaspa: ^0.1.0  # For Kaspa blockchain interactions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.0
  mockito: ^5.4.2

# Flutter configuration
flutter:
  uses-material-design: true
